---
- name: 2. INSTALL MARIADB - Server and Databases Setup
  hosts: all
  become: true

  tasks:
    - name: Install MariaDB Server and PyMySQL package
      ansible.builtin.apt:
        name:
          - mariadb-server
          - python3-pymysql
        update_cache: true

    - name: Start and enable MariaDB service
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    - name: Check if MariaDB root password is already set
      ansible.builtin.shell: "mysql -u root -p'{{ mariadb_root_password }}' -e 'SELECT 1;'"
      register: mariadb_root_check
      failed_when: mariadb_root_check.rc not in [0, 1]
      changed_when: false
      ignore_errors: true

    - name: Set MariaDB root password if not set
      community.mysql.mysql_user:
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ mariadb_root_password }}'
        state: present
      when: mariadb_root_check.failed

    - name: Create .my.cnf for root
      ansible.builtin.copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password={{ mariadb_root_password }}
        owner: root
        mode: '0600'

    - name: Create SQL script
      ansible.builtin.copy:
        content: |
          CREATE DATABASE IF NOT EXISTS {{ mariadb_database }};
          CREATE DATABASE IF NOT EXISTS {{ mariadb_test_database }};
          CREATE USER IF NOT EXISTS '{{ mariadb_user }}'@'localhost' IDENTIFIED BY '{{ mariadb_password }}';
          GRANT ALL PRIVILEGES ON {{ mariadb_database }}.* TO '{{ mariadb_user }}'@'localhost';
          GRANT ALL PRIVILEGES ON {{ mariadb_test_database }}.* TO '{{ mariadb_user }}'@'localhost';
          FLUSH PRIVILEGES;
        dest: /tmp/setup.sql
        mode: '0644' # Añadido modo

    - name: Import SQL script
      ansible.builtin.command: bash -c "mysql < /tmp/setup.sql"
      changed_when: true # Forzamos changed_when: true ya que ejecuta SQL DDL/DCL

    - name: Remove temporary SQL script
      ansible.builtin.file:
        path: /tmp/setup.sql
        state: absent
