---
- name: 3. MARIADB SCRIPTS - Set Permissions and Initialize DB
  hosts: all
  become: true

  vars:
    common_environment:
      FLASK_APP_NAME: "{{ flask_app_name }}"
      FLASK_ENV: "{{ flask_env }}"
      DOMAIN: "{{ domain }}"
      MARIADB_HOSTNAME: "{{ mariadb_hostname }}"
      MARIADB_PORT: "{{ mariadb_port }}"
      MARIADB_DATABASE: "{{ mariadb_database }}"
      MARIADB_TEST_DATABASE: "{{ mariadb_test_database }}"
      MARIADB_USER: "{{ mariadb_user }}"
      MARIADB_PASSWORD: "{{ mariadb_password }}"
      MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      WORKING_DIR: "{{ working_dir }}"

  tasks:
    - name: Set permissions for wait-for-db.sh
      ansible.builtin.file:
        path: "{{ working_dir }}scripts/wait-for-db.sh"
        mode: '0755'
        state: file
      environment: "{{ common_environment }}"

    - name: Set permissions for init-testing-db.sh
      ansible.builtin.file:
        path: "{{ working_dir }}scripts/init-testing-db.sh"
        mode: '0755'
        state: file
      environment: "{{ common_environment }}"

    - name: Wait for MariaDB to be ready
      ansible.builtin.shell: |
        {{ working_dir }}scripts/wait-for-db.sh
      args:
        executable: /bin/bash
      environment: "{{ common_environment }}"
      changed_when: false

    - name: Initialize the database
      ansible.builtin.shell: |
        {{ working_dir }}scripts/init-testing-db.sh
      args:
        executable: /bin/bash
      environment: "{{ common_environment }}"
      changed_when: true  # Forzamos changed_when: true ya que inicializa la DB
