---
- name: 4. INSTALL DEPENDENCIES - Python, VENV, and Packages
  hosts: all
  become: true

  tasks:
    - name: Add deadsnakes PPA for installing Python 3.12
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: true

    - name: Update the system and install Python 3.12 and dependencies
      ansible.builtin.apt:
        name:
          - python3.12
          - python3.12-venv
          - mariadb-client
        state: present

    - name: Install pip and setuptools for Python 3.12 from source
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
        mode: '0755'

    - name: Install pip and setuptools for Python 3.12
      ansible.builtin.command: python3.12 /tmp/get-pip.py # Cambiamos shell por command ya que no es necesario aquí
      changed_when: true # Forzamos changed_when: true para reflejar la instalación

    - name: Upgrade pip and setuptools for Python 3.12
      ansible.builtin.shell: |
        python3.12 -m pip install --upgrade pip setuptools
      args:
        executable: /bin/bash
      changed_when: false

    - name: Set up the Python 3.12 virtual environment
      ansible.builtin.command: python3.12 -m venv {{ working_dir }}vagrant_venv
      args:
        creates: "{{ working_dir }}vagrant_venv/bin/activate"

    - name: Activate the virtual environment and install dependencies
      ansible.builtin.shell: |
        source {{ working_dir }}vagrant_venv/bin/activate
        pip install --upgrade pip
        cd {{ working_dir }}
        pip install -r requirements.txt
        pip install -e ./
      args:
        executable: /bin/bash
      changed_when: false

    - name: Descargar Modelos NLTK y spaCy
      ansible.builtin.shell: |
        source {{ working_dir }}vagrant_venv/bin/activate
        cd {{ working_dir }}
        python scripts/download_nlp_resources.py
      args:
        executable: /bin/bash
      changed_when: false

    - name: Security audit with pip-audit
      ansible.builtin.shell: |
          source {{ working_dir }}vagrant_venv/bin/activate
          pip install pip-audit
          pip-audit || true
      args:
        executable: /bin/bash
      changed_when: false
