---
- name: 5. RUN APP - Setup App Context and Start Server
  hosts: all
  become: true

  vars:
    common_environment:
      FLASK_APP_NAME: "{{ flask_app_name }}"
      FLASK_ENV: "{{ flask_env }}"
      DOMAIN: "{{ domain }}"
      MARIADB_HOSTNAME: "{{ mariadb_hostname }}"
      MARIADB_PORT: "{{ mariadb_port }}"
      MARIADB_DATABASE: "{{ mariadb_database }}"
      MARIADB_TEST_DATABASE: "{{ mariadb_test_database }}"
      MARIADB_USER: "{{ mariadb_user }}"
      MARIADB_PASSWORD: "{{ mariadb_password }}"
      MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      WORKING_DIR: "{{ working_dir }}"
      FERNET_KEY: "{{ fernet_key }}"
      FAKENODO_URL: "{{ fakenodo_url }}"

  tasks:

    - name: Add webhook to .moduleignore
      ansible.builtin.shell: echo "webhook" > {{ working_dir }}.moduleignore
      args:
        executable: /bin/bash
      environment: "{{ common_environment }}"
      changed_when: false

    - name: Set database with Rosemary
      ansible.builtin.shell: |
        source {{ working_dir }}vagrant_venv/bin/activate
        cd {{ working_dir }}
        flask db upgrade
        rosemary db:seed -y --reset
      args:
        executable: /bin/bash
      environment: "{{ common_environment }}"
      changed_when: true # Forzamos changed_when: true ya que modifica la DB

    - name: Run Flask application
      ansible.builtin.shell: |
        source {{ working_dir }}vagrant_venv/bin/activate
        cd {{ working_dir }}
        nohup flask run --host=0.0.0.0 --port=5000 --reload --debug > app.log 2>&1 &
      args:
        executable: /bin/bash
      environment: "{{ common_environment }}"
      async: 1
      poll: 0
      changed_when: true # Asumimos que el proceso cambia si se lanza

    - name: Remove old app.log files
      ansible.builtin.file:
        path: "{{ working_dir }}app.log.*"
        state: absent
