---
- name: 6. UTILITIES - Configure Vagrant User Environment
  hosts: all
  become: true

  tasks:

    - name: Add commands to .bashrc
      ansible.builtin.lineinfile:
        path: /home/vagrant/.bashrc
        line: '{{ item }}'
        create: true
        mode: '0644' # Añadido modo para evitar risky-file-permissions
      with_items:
        - 'source {{ working_dir }}vagrant_venv/bin/activate'
        - 'cd {{ working_dir }}'
      when: ansible_user == 'vagrant'
