"""empty message

Revision ID: c7d2761517b6
Revises: 9f530c2a21a5
Create Date: 2025-12-03 13:33:57.344026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'c7d2761517b6'
down_revision = '9f530c2a21a5'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)

    # ----------- TABLAS -----------
    # csv_model
    if 'csv_model' not in inspector.get_table_names():
        op.create_table(
            'csv_model',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('data_set_id', sa.Integer(), nullable=False),
            sa.Column('fm_meta_data_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id']),
            sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id']),
            sa.PrimaryKeyConstraint('id')
        )

    # feature_model
    if 'feature_model' in inspector.get_table_names():
        op.drop_table('feature_model')

    # ----------- COLUMNAS -----------

    # ds_metrics
    columns_ds_metrics = [c['name'] for c in inspector.get_columns('ds_metrics')]
    if 'number_of_csv' not in columns_ds_metrics:
        with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
            batch_op.add_column(sa.Column('number_of_csv', sa.String(length=120), nullable=True))
    if 'number_of_features' in columns_ds_metrics:
        with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
            batch_op.drop_column('number_of_features')

    # file
    columns_file = [c['name'] for c in inspector.get_columns('file')]
    if 'csv_model_id' not in columns_file:
        with op.batch_alter_table('file', schema=None) as batch_op:
            batch_op.add_column(sa.Column('csv_model_id', sa.Integer(), nullable=False))
            batch_op.drop_constraint(batch_op.f('file_ibfk_1'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'csv_model', ['csv_model_id'], ['id'])
    if 'feature_model_id' in columns_file:
        with op.batch_alter_table('file', schema=None) as batch_op:
            batch_op.drop_column('feature_model_id')

    # fm_meta_data
    columns_fm_meta = [c['name'] for c in inspector.get_columns('fm_meta_data')]
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        if 'csv_filename' not in columns_fm_meta:
            batch_op.add_column(sa.Column('csv_filename', sa.String(length=120), nullable=False))
        if 'csv_version' not in columns_fm_meta:
            batch_op.add_column(sa.Column('csv_version', sa.String(length=120), nullable=True))
        if 'uvl_filename' in columns_fm_meta:
            batch_op.drop_column('uvl_filename')
        if 'uvl_version' in columns_fm_meta:
            batch_op.drop_column('uvl_version')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('csv_version')
        batch_op.drop_column('csv_filename')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_ibfk_1'), 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('csv_model_id')

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_features', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('number_of_csv')

    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('csv_model')
    # ### end Alembic commands ###
